### ISSUE TITLE
Add sub-commands

### ISSUE THREAD

**Issue by ghost** [jnoortheen/xontrib-commands#7]
Hi, I would like to suggest an interface to add sub-commands.

As the [`arger`](https://jnoortheen.github.io/arger/) library supports [sub-commands](https://jnoortheen.github.io/arger/examples/2-sub-commands/) the idea would be to make a practical interface to be used by xontrib-commands.

I managed to do it with the following code:

<details>

```python
from inspect import isclass

from arger import Argument
from xontrib_commands import argerize


class Arger(argerize.Arger):
    def add_cmds(self, _class):
        self.description = _class.__doc__

        cmds = (
            getattr(_class, attr)
            for attr in dir(_class)
            if not attr.startswith('_')
        )
        for cmd in cmds:
            self.add_cmd(cmd)


class SubCommand(argerize.Command):
    def build(self) -> "Arger":
        _class = None
        if isclass(self.kwargs.get('func')):
            _class = self.kwargs.pop('func')

        _arger = Arger(**self.kwargs)
        if _class:
            _arger.add_cmds(_class)
        return _arger


@SubCommands.reg_no_thread
class _todo:
    """Todo manager."""

    @staticmethod
    def ls(
        name: Argument(type=str) = None,
        description: Argument(type=str) = None,
        status: Argument(type=bool) = None,
    ):
        """
        List all todos.

        Parameters
        ----------
        name:
            Todo name
        description:
            Todo description
        status:
            Todo status
        """

    @staticmethod
    def add(
        name: Argument(type=str, required=True) = None,
        status: Argument(type=bool, required=True) = None,
        description: Argument(type=str) = None,
    ):
        """
        Add a todo

        Parameters
        ----------
        name:
            Todo name
        status:
            Todo status
        description:
            Todo description
        """
```

</details>

Maybe the code is not robust, but it works with staticmethod and classmethod.

If it is of interest to add this functionality and if this implementation is interesting, I can send a pull request adding and documenting this class.

I believe it would be very useful to have a way to add sub-commands, so if the above implementation is not interesting or needs to be improved, I'm at your disposal.

**Comment by jnoortheen** [comment]
Yes it would be helpful in some instances. To implement this, there would be another way to do this. Instead of building the `Arger` instance inside the code(`Command.build()`), it can be passed directly to the `Command.reg` . I will create a PR with this.
